### ISSUE TITLE
Rewrite redux mapping in child components

### ISSUE THREAD

**Issue by Crecket** [DennisSnijder/BunqWeb#15]
Loading all actions and props in the Main component and passing them down to all the pages isn't recommended and results in unused code and a bloated Main component

Moving the required actions/props to the correct child components should cleanup the Main component and make things a lot easier to work with.

## Acceptance Criteria
 - Unused Redux props/actions are removed from the Main component
 - Actions/Props are connected in the target Child component

**Comment by kennethvandenberghe** [comment]
@Crecket Where in the documentations do you see the part that no longer recommends that you pass actions/props top down?

**Comment by Crecket** [comment]
I edited the issue as it wasn't very clear. What I meant to say was that loading all actions/props in the Main component and passing everything down from that single container is no longer recommended. Redux used to write their examples like that and I haven't worked on other projects where they did it differently until now

Loading actions/props only when a component needs it prevents unnecessary code. This also helps when we are code-splitting since we no longer load things we don't need.

Mainly I want to prevent and remove [this stuff](https://github.com/DennisSnijder/BunqWeb/blob/cce0361da0dbc6f898106870f3d8f222bb96cd55/resources/React/Components/Main.jsx#L118) 😄
